### PR TITLE
lxqt default programs

### PR DESCRIPTION
**Pull request by Wyn10**
Will work when https://github.com/Antergos/antergos-packages/pull/59 is also merged.

### CODE REVIEW

**Comment by karasu** [comment]
I always try to stay away from packages that compile directly from git or they should, at least, have a tag version (I haven't checked these ones). If not, then these type of packages break very often.

**Comment by lots0logs** [comment]
@Wyn10 Packages from the AUR cannot be used in packages.xml. If there is a package that we deem necessary which is only in the AUR then we will package it ourselves in our repo. If there is a strong case for any of the AUR packages in this PR please let us know so we can decide how to proceed. Thanks!

**Comment by Wyn10** [comment]
@karasu Was using the [Arch wiki as guidance](https://wiki.archlinux.org/index.php/Desktop_environment#Comparison_of_desktop_environments) for the default packages.  The packaged I also pulled in the antergos-packages repo.

@lots0logs Being pulled here: https://github.com/Antergos/antergos-packages/pull/59

Wanted to keep to the desktop without any compromises.

**Comment by lots0logs** [comment]
merged in c409d8290dee6f7ece5ffa9b46d69ea70ffec913

**Pull request closed without merging**
