### PR TITLE
Mousepad Openbox

### PR DESCRIPTION
**Pull request by Wyn10**
#394

### CODE REVIEW

**Comment by lots0logs** [comment]
@Wyn10 I commented on the forum post, please check it. Thanks.

**Comment by Wyn10** [comment]
@lots0logs I may have jumped the gun on this one, but isn't mousepad the default for openbox, not leafpad?

**Comment by karasu** [comment]
mousepad -> XFCE
leafpad -> LXDE
There's really no default editor for Openbox, as it's "only" a Window Manager. It seemed to me that leafpad had more functions (so it was more complete), but I can be wrong because I don't use any of the two editors.

**Comment by Wyn10** [comment]
@karasu 

>i only installed mousepad because the links for editing openbox in the menu were configured to use mousepad. so like to edit autostart it was asking for mousepad.

[That sounds like a openbox default.](http://forum.antergos.com/topic/2770/cnchi-does-not-pull-in-mousepad-when-installing-openbox-desktop/5)

**Pull request merged**
