### PR TITLE
Properly named Plasma

### PR DESCRIPTION
**Pull request by Wyn10**
People on irc have been assuming "KDE" is 4.  KDE5 is named KDE Plasma, the updated version.

### CODE REVIEW

**Comment by lots0logs** [comment]
I'm not sure about this. KDE has always referred to its desktop workspace as ***Plasma*** (ever since KDE4 was released). I don't think anything has changed in that respect. Furthermore, if we did make the change you propose then we'd need to change GNOME to be **GNOME Shell**. IMO, I don't think its necessary but lets see what @karasu thinks!

**Comment by Wyn10** [comment]
KDE's [announcement page](https://www.kde.org/announcements/plasma5.0/) says Plasma 5, they don't include KDE in the name since it's already on KDE's site.

**Comment by lots0logs** [comment]
Yes, because that's an announcement for Plasma 5. That doesnt mean that KDE is not still KDE. Like I said, before Plasma 5 there was Plasma 4.

**Comment by karasu** [comment]
If you want to put KDE5 we should also put Gnome3... and I don't like it. I must agree with @lots0logs in this one.

Cheers!

**Pull request closed without merging**
