### PR TITLE
Changed 'Gnome' to 'GNOME'

### PR DESCRIPTION
**Pull request by xeriouxi**
Changed 'Gnome' in the menu and description to say 'GNOME' instead

### CODE REVIEW

**Comment by axaxs** [comment]
Why

**Comment by karasu** [comment]
I'm not again this, but not now as it will break all translations... let's keep it open and discuss after Cnchi 0.10 has been released

**Comment by karasu** [comment]
GNOME is an acronym, so I agree it should be in uppercase. Will do in dev version.

Thanks!

**Comment by axaxs** [comment]
Thanks.  I didn't intend to be quite so dismissive/short but was asking the reason (regardless of how a company/person spells things, I prefer properness).  A commit message should probably explain reasoning for such an otherwise arbitrary change.  It didn't occur to me it was an acronym at some point, but Wikipedia agrees, so listing here for future reference if needed.
The name "GNOME" was initially an acronym of GNU Network Object Model Environment, referring to the original intention of creating a distributed object framework similar to Microsoft's OLE,[36] but the acronym was eventually dropped because it no longer reflected the vision of the GNOME project

**Pull request closed without merging**
