### PR TITLE
Update packages.xml

### PR DESCRIPTION
**Pull request by Wyn10**
Added conflict.
Added flash for firefox.

### CODE REVIEW

**Comment by lots0logs** [comment]
I'll have to take a closer look and refresh my memory on how we've implemented the `conflicts` functionality. I want to say that only one package out of two conflicting packages should have the conflict attribute set (otherwise how would Cnchi choose which package wins?) I'll try and check it asap (unless @karasu can shed some light on the matter before I get to it hehe)

**Comment by Mikaela** [comment]
Isn't it time to let Flash die already? In my usage the only places where I encounter suggestion to install flash are:

* facebook photo upload (it gives me browse buttons and select manually which photos to upload)
* speedtest.net (just use speedof.me instead)

In case you believe that it's not time for Flash to be killed with it's holes yet, I at least give :-1: to Adobe's `flashplugin` as it is dead and only receives security updates. `freshplayerplugin` from AUR would make more sense as it makes it possible to use pepperflash (as in Chrome and still developed) with Firefox & others.

**Comment by Wyn10** [comment]
@lots0logs 

Currently even with firefox selected, it still downloads chromium and does not install it.  I think because chromium is downloaded anyway, the pepperflash package is also installed.

Also reference to this issue #328

@Mikaela Flash is too embedded into the web to kill so quickly.

**Comment by Mikaela** [comment]
@Wyn10 Where do you actively encounter flash and have no other option than to use it?

**Comment by Wyn10** [comment]
@Mikaela Games/Streams

**Comment by Mikaela** [comment]
Games I am not familiar with, but streams should be moving to HTML5 and possibly even work with it if you disable flash.

**Comment by karasu** [comment]
@Wyn10 : Added in 0.11.50
firefox will take precedence over chromium if the former is selected.

@Mikaela : I think freshplayerplugin is a great idea, but I used it like a month ago and had a lot of problems with it (I don't remember which ones, just that it didn't work for me).

**Comment by Mikaela** [comment]
> I think freshplayerplugin is a great idea, but I used it like a month ago and had a lot of problems with it (I don't remember which ones, just that it didn't work for me).

I cannot comment this as I have just tested that it works before marking it as "never load" in Firefox plugin settings.

On streaming, Google is going to release twitch.tv competitor today with HTML5 so more reasons to kill flash. http://arstechnica.com/gaming/2015/08/youtube-gaming-googles-twitch-tv-competitor-launches-tomorrow/

**Pull request closed without merging**
