### PR TITLE
Lvm advanced fix

### PR DESCRIPTION
**Pull request by ial-su3**
The initcpio lvm hook was never added during my install.

I have the mounts:
/dev/sda1/ boot
vg0/antergos /

This failed to pass the root and noboot check, hence no lvm hook, by removing the noboot it installed perfectly

### CODE REVIEW

**Comment by lots0logs** [comment]
@karasu You are more familiar with this area, what are your thoughts?

**Comment by axaxs** [comment]
I don't understand this change.

The way it was written is that if the partition is "/" and there is no
/boot, set the boot flag on the current device since it is assumed /boot
falls under / (like say, ubuntu).  With this change, if there are distinct
/ and /boot, both get the boot flag set...

**Comment by lots0logs** [comment]
Exactly what I was thinking which is why I wanted to get another pair of eyes on it :smile:

**Comment by ial-su3** [comment]
Yes, sorry I was too quick with this.  I'm now at all not sure why I had the issue I did, but this is not a fix.

**Pull request closed without merging**
