### PR TITLE
Game support

### PR DESCRIPTION
**Pull request by Wyn10**
Added game support in feature list.  With more gamers moving over to linux this will be a very useful feature in getting started.  Steam is one of the main supported clients for linux games,  PlayOnLinux is a easy way to manage games in wine without having to do it manually.

Still trying to figure out where the feature icons are coming from, some guidance is appreciated.

### CODE REVIEW

**Comment by lots0logs** [comment]
Thanks @Wyn10 ! Either myself or @karasu will review this ASAP :smile:

**Comment by Wyn10** [comment]
Has been tested in Xfce and kde, no isses.

**Comment by karasu** [comment]
Looks ok to me. Let's just wait a bit until this release "stabilises"
itself, but will add it for sure. Thanks @Wyn10 !

2015-08-20 3:54 GMT+02:00 Wyn <notifications@github.com>:

> Has been tested in Xfce and kde, no isses.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Antergos/Cnchi/pull/375#issuecomment-132849148>.
>



-- 

No podran res davant un poble unit, alegre i combatiu
There's nothing they can do against united, cheerful and combative people.

**Comment by karasu** [comment]
Added to Cnchi 0.11.47 (will be released as 0.12) Thanks!

**Pull request closed without merging**
