### PR TITLE
Disabling light-locker in light-locker-settings does nothing.

### PR DESCRIPTION
**Pull request by maxammann**
We need to start light-locker in Xsession because gnome starts its screensaver instead. But if we do so disabling it in light-locker-settings does nothing.

Therefore we need to check if it's enabled in $HOME/.config/autostart/light-locker.desktop

The fix is more like a workaround, but I think this is no probem as the development on light-locker seems to have stopped. It's also tested and works.

### CODE REVIEW

**Comment by lots0logs** [comment]
@maxammann Sorry for the delay. Have you tested this? I'm not sure that `$HOME` is available at the time that is executed. Also it would break backwards compatibility. I will try and find some time soon to come up with a better way to do this so that it works and can be disabled at-will by the user.

**Comment by maxammann** [comment]
@lots0logs yes, its tested and $HOME is available. Just test to disable light-locker and then check if it's running after a reboot (pidof light-locker). For me its still running.

**Comment by Yoshi2889** [comment]
Looks like this no longer exists in postinstall.sh, or is set up for GNOME.

The light-locker extension should take care of this for gnome, too.

**Comment by maxammann** [comment]
True, fixed by problem back that at least :D

**Pull request closed without merging**
