### PR TITLE
Made Mate Desktop Active

### PR DESCRIPTION
**Pull request by doeixd**
Gave it the ability to add desktop shortcuts to take care of issue #584

### CODE REVIEW

**Comment by karasu** [comment]
@lots0logs and what about this one?

**Comment by lots0logs** [comment]
@karasu Honestly, I kind of feel like we should stick to the default setting. This option can be easily changed by the user in Mate's control panel if they so desire.

**Comment by karasu** [comment]
OK.

Please, Close this then (I'm on my phone)

El dijous, 12 de maig de 2016, Dustin Falgout <notifications@github.com> va
escriure:

> @karasu <https://github.com/karasu> Honestly, I kind of feel like we
> should stick to the default setting. This option can be easily changed by
> the user in Mate's control panel if they so desire.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Antergos/Cnchi/pull/586#issuecomment-218605293>
>


-- 
Enviat amb el meu Iphone

**Comment by prescott66** [comment]
So you think it is ok, when you defaultly dont see icons on the desktop??

**Comment by Mikaela** [comment]
I don't think MATE disables desktop icons by default and this sometimes causes confusion at IRC and we must advice to install MATE-Tweak.

I think it would be the best if the desktop icons were visible by default.

**Pull request closed without merging**
