### PR TITLE
Update desktop_info.py

### PR DESCRIPTION
**Pull request by raonyguimaraes**
Fix issue #582 by adding LAMP option while installing a Desktop Environment.

### CODE REVIEW

**Comment by karasu** [comment]
Have you tested this? I can't remember if this was a "design" choice or it was some kind of problem if using this while also installing a DE.

**Comment by lots0logs** [comment]
@karasu haha, that's exactly why I didnt merge it. I was waiting for you :laughing:

**Comment by raonyguimaraes** [comment]
Sorry guys, I just tested and there was a problem after rebooting the machine. The DE is not coming up.

I will investigate it further.

**Comment by karasu** [comment]
Be warned there is a known Virtualbox bug... Check our forums 😉

El dimarts, 26 d’abril de 2016, Raony Guimarães Corrêa Do Carmo Lisboa
Cardenas <notifications@github.com> va escriure:

> Sorry guys, I just tested and there was a problem after rebooting the
> machine. The DE is not coming up.
>
> I will investigate it further.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Antergos/Cnchi/pull/583#issuecomment-214790777>
>


-- 
Enviat amb el meu Iphone

**Comment by raonyguimaraes** [comment]
I just tested both options with nginx and apache using Boxes and they worked fine. 

This is good to go and ready to be merged. :)

Another suggestion for the future would be to add this option in antergos-welcome, to make it look more like it's downstream project mate-welcome.

Thank you guys for making such an awesome installer!

**Comment by raonyguimaraes** [comment]
Still need to do some work on this.

**Comment by lots0logs** [comment]
Closing for now. Please do open a new PR if you find the time to finish this in the future. Thanks!

**Pull request closed without merging**
